### ISSUE TITLE
Cannot find package 'ioredis'

### ISSUE THREAD

**Issue by xkungfu** [bytedo/gmf.core#1]
`internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ioredis' imported from /nnnroot/gmf.core/node_modules/@gm5/session/lib/redis-store.js
    at packageResolve (internal/modules/esm/resolve.js:594:9)
    at moduleResolve (internal/modules/esm/resolve.js:633:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
`
ioredis未安装。

**Comment by yutent** [comment]
不好意思, 项目在重构中, 还有些依赖没有补充完整。
-----
现在已经好了, 重新安装一下依赖就行
